* simple-resturant api
Simple restaurant api project is a part of Paidy technical assesment.

* Assignment (breif)
Create a restaurant application which accepts menu items from various serving staff in the restaurant. This application must then store the item along with a cooking time for the item to be completed. The application must be able to give a quick snapshot of any or all items on its list at any time. It must also be able to remove specific orders from the list of orders on demand.

The full assignment and can be found at [[https://github.com/paidy/interview/blob/master/SimpleRestaurantApi.md][Paidy Simple Resturant Api]].

** Actors
+ Application : a “server” and accepting calls from devices carried by restaurant staff to process guest’s menu orders.
+ Client : Multiple "tablets" carried by restaurant staff to take orders.

** Requirements
+ The server API MUST fully follow REST API principles and present a set of HTTP endpoints to connect to.
+ The client (the restaurant staff “devices” making the requests) MUST be able to: add one or more items with a table number, remove an item for a table, and query the items still remaining for a table.
+ The application MUST, upon creation request, store the item, the table number, and how long the item will take to cook.
+ The application MUST, upon deletion request, remove a specified item for a specified table number.
+ The application MUST, upon query request, show all items for a specified table number.
+ The application MUST, upon query request, show a specified item for a specified table number.
+ The application MUST accept at least 10 simultaneous incoming add/remove/query requests.
+ The client MAY limit the number of specific tables in its requests to a finite set (at least 100).
+ The application MAY assign a length of time for the item to prepare as a random time between 5-15 minutes.
+ The application MAY keep the length of time for the item to prepare static (in other words, the time does not have to be counted down in real time, only upon item creation and then removed with the item upon item deletion).

*** Assumptions
+ The time to prepare does not have to be kept up-to-date. It can also just be generated as some random amount of time between 5 and 15 minutes and kept static from then on.
+ The table and items can be identified in any chosen manner, but it has to be consistent. So if a request comes in for table "4", for example, any other requests for table "4" must refer to the same table.
+ “Clients” can be simulated as simple threads in a main() function calling the main server application with a variety of requests. There should be more than one, preferably around 5-10 running at any one time. => This is available under the clients "Simulation" menu, please try it out! (Supports simultaneous ~1000 clients, then db breaks, could be resolved by using locks, however, locks have too much overhead when it comes to performance!)

* How to
** Prerequisites
*** Building/running
**** Docker (Recommended)
+ Any modern version of docker. (https://docs.docker.com/build/)
+ Any version of docker compose.(https://docs.docker.com/compose/)

This project comes with an docker image to reduce the overhead of setting up the build system locally.

The motivation for recommending this method is not performance but convenience for the reviewer. Please keep this in mind.

**** Local
#+name: rustup
#+begin_src shell
rustup --version
#+end_src

#+RESULTS:
: rustup 1.27.1 (54dd3d00f 2024-04-24)

#+name: Cargo
#+begin_src shell
cargo --version
#+end_src

#+RESULTS:
: cargo 1.79.0 (ffa9cf99a 2024-06-03)

#+name: Postgresql libs
#+begin_src shell
pacman -Q --info postgresql-libs
#+end_src

#+RESULTS: Postgresql libs
| Name         | :      | postgresql-libs             |                        |                        |               |                   |          |          |      |      |
| Version      | :      | 16.3-4                      |                        |                        |               |                   |          |          |      |      |
| Description  | :      | Libraries                   | for                    | use                    | with          | PostgreSQL        |          |          |      |      |
| Architecture | :      | x86_64                      |                        |                        |               |                   |          |          |      |      |
| URL          | :      | https://www.postgresql.org/ |                        |                        |               |                   |          |          |      |      |
| Licenses     | :      | PostgreSQL                  |                        |                        |               |                   |          |          |      |      |
| Groups       | :      | None                        |                        |                        |               |                   |          |          |      |      |
| Provides     | :      | libecpg.so=6-64             | libecpg_compat.so=3-64 | libpgtypes.so=3-64     | libpq.so=5-64 | postgresql-client |          |          |      |      |
| Depends      | On     | :                           | glibc                  | krb5                   | libldap       | lz4               |  openssl | readline | zlib | zstd |
| Optional     | Deps   | :                           | None                   |                        |               |                   |          |          |      |      |
| Required     | By     | :                           | None                   |                        |               |                   |          |          |      |      |
| Optional     | For    | :                           | qt5-base               | qt6-base               |               |                   |          |          |      |      |
| Conflicts    | With   | :                           | postgresql-client      |                        |               |                   |          |          |      |      |
| Replaces     | :      | None                        |                        |                        |               |                   |          |          |      |      |
| Installed    | Size   | :                           | 8.5                    | MiB                    |               |                   |          |          |      |      |
| Packager     | :      | Antonio                     | Rojas                  | <arojas@archlinux.org> |               |                   |          |          |      |      |
| Build        | Date   | :                           | Sun                    | 1                      | Sep           | 2024              | 06:53:11 | PM       | UTC  |      |
| Install      | Date   | :                           | Fri                    | 15                     | Nov           | 2024              | 02:39:12 | AM       | UTC  |      |
| Install      | Reason | :                           | Explicitly             | installed              |               |                   |          |          |      |      |
| Install      | Script | :                           | No                     |                        |               |                   |          |          |      |      |
| Validated    | By     | :                           | Signature              |                        |               |                   |          |          |      |      |
|              |        |                             |                        |                        |               |                   |          |          |      |      |

#+name: Alternative: install libpq-dev
#+begin_src
apt install libpq-dev
#+end_src

** Overview
The project comes with a Makefile that has a few commands to help you run the project.
Please refer to the help rule for more information about the specifics of each rule.

#+begin_src sh
make help
#+end_src

To interact with the provided cargo makefile, please use the "task" rule.

#+begin_src sh
# For example
make task run
#+end_src

** Run
*** Docker
To run both server and client.
#+begin_src sh
make run
#+end_src

To run a specific module
#+begin_src sh
make run server

make run client
#+end_src

*** Local
#+name: Both server and client
#+begin_src sh
make task run
#+end_src

#+name: Server only
#+begin_src sh
make task server
#+end_src

#+name: Client only
#+begin_src sh
make task client
#+end_src
** Test
#+begin_src sh
make test
#+end_src

** Migrate db
Migration is done automatically on start, but in case you'd need to migrate it locally.

#+begin_src sh
make task migrate
#+end_src

** Access swagger

Swagger can be found on <HOST>:<PORT>/docs
